spring:
  application:
    name: crud-example

datasource:
  customs:
    query-timeout: 20
  my-connection:
    jdbc-url: jdbc:postgresql://localhost:5432/os_systems
    username: walrus
    password: 12345
    maximum-pool-size: 10
    pool-name: "crud-pool"
    auto-commit: true


